sonar.projectKey=spring-cloud-app
sonar.projectName=spring-cloud-app
sonar.host.url=http://host.docker.internal:9000
sonar.login=YOUR_TOKEN

sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml