apiVersion: v1
kind: ConfigMap

metadata:
  name: springboot-config

data:
  SPRING_PROFILES_ACTIVE: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/{{ .Values.mysql.database }}