apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "springboot-cloud.fullname" . }}
  labels:
    {{- include "springboot-cloud.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "springboot-cloud.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "springboot-cloud.selectorLabels" . | nindent 8 }}

    spec:

      containers:

        - name: springboot-cloud
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: springboot-config
                  key: SPRING_PROFILES_ACTIVE

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: springboot-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password

          resources:
            {{- toYaml .Values.resources | nindent 12 }}