replicaCount: 2

image:
  repository: 9708156765/springboot-cloud
  pullPolicy: Always
  tag: latest

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8088
  targetPort: 8088

container:
  port: 8088

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  SPRING_PROFILES_ACTIVE: docker

#########################################################
# MySQL Configuration
#########################################################

mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent

  database: springCloudAppDB

  username: springuser

  password: Spring@123

  rootPassword: Root@123

  service:
    type: ClusterIP
    port: 3306

  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 2Gi